### ISSUE TITLE
Ejercicio 1 Gomez Hernandez Alyn Ximena

### ISSUE THREAD

**Issue by AlynGomez12** [SistemasTecTlaxiaco/actividad-4-mapa-mental-AlynGomez12#2]
[conjuntos y subconjuntos.pdf](https://github.com/user-attachments/files/17079998/conjuntos.y.subconjuntos.pdf)

**Comment by irwingsael** [comment]
Exposición de Ideas Centrales:5/5
Redacción y Ortografía:5/5
Presentación visual:5/5
Referencias:5/5
Calificación Final:20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado..
